CREATE TABLE TBL_CLIENTE
(
  DOCUMENTO VARCHAR(15),
  COD_TIPO_DOCUMENTO INT,
  NOMBRES VARCHAR(30),
  APELLIDOS VARCHAR(30),
  DIRECCION VARCHAR(20),
  TELEFONO VARCHAR(20),
  EMAIL   VARCHAR(20),
  FECHA_NACIMIENTO DATETIME
);

