CREATE TABLE TBL_FACTURA
(
  NUM_FACTURA VARCHAR(20),
  CODIGO_CLIENTE VARCHAR(15),
  NOMBRE_EMPLEADO VARCHAR(30),
  FECHA_FACTURACION DATETIME,
  TOTAL_FACTURA DECIMAL(10,0),
  IVA DECIMAL(10,0)
);

